package vrds.model.meta;

public enum TODOTag {
    BUG, CAST, MISSING_IMPLEMENTATION, INHERITENCE, DELETE, REVERT, TRANSACTION, PROCESS_TO_TASK_RELATIONSHIP, SINGLETON, SPECIFICATION_REQUIRED, OPTIMIZATION_TARGET_CANDIDATE, SIMPLIFICATION, MISSING_EXCEPTION_HANDLING;
}
